# 06.2 Data Cleaning - Tags

Thanks to the previous step, Data Profiling - Tags

In [1]:
import datetime
import os
import time
import pandas as pd 
import requests
import urllib3
import json
import sys
import numpy as np
import math

pd.options.display.max_colwidth = 1000
pd.set_option('display.max_columns', None)

In [2]:
file = r'C:\Users\leona\OneDrive\Desktop\Tesi\Pipeline\Datasets\Pipeline\IocSegnalations\PostDataIntegration\Tags.csv'

In [3]:
df = pd.read_csv(file, low_memory = False )
df

       ID_ENTRY      source                     tag
0       2711900    URL Haus                  hajime
1       2711899    URL Haus              socgholish
2       2711898    URL Haus                    mozi
3       2711897    URL Haus  dropped by smokeloader
4       2711896    URL Haus                nanocore
...         ...         ...                     ...
31547   1163859  Threat Fox                     rat
31548   1163860  Threat Fox                     rat
31549   1163860  Threat Fox                nanocore
31550   1163861  Threat Fox               remcosrat
31551   1163861  Threat Fox                     rat

[31552 rows x 3 columns]

# Data Cleaning

### Error Correction - Missing value
Drop a row if one of the sub columns 'tag' , 'source' or 'ID_ENTRY' is NaN

In [4]:
df.dropna(subset=['ID_ENTRY', 'tag', 'source'], inplace=True)
df = df.reset_index(drop = True)
df

       ID_ENTRY      source                     tag
0       2711900    URL Haus                  hajime
1       2711899    URL Haus              socgholish
2       2711898    URL Haus                    mozi
3       2711897    URL Haus  dropped by smokeloader
4       2711896    URL Haus                nanocore
...         ...         ...                     ...
31547   1163859  Threat Fox                     rat
31548   1163860  Threat Fox                     rat
31549   1163860  Threat Fox                nanocore
31550   1163861  Threat Fox               remcosrat
31551   1163861  Threat Fox                     rat

[31552 rows x 3 columns]

### Duplicate Detection - Drop Duplicates
The duplicate rows are dropped

In [5]:
df = df.drop_duplicates()
df = df.reset_index(drop = True)
df

       ID_ENTRY      source                     tag
0       2711900    URL Haus                  hajime
1       2711899    URL Haus              socgholish
2       2711898    URL Haus                    mozi
3       2711897    URL Haus  dropped by smokeloader
4       2711896    URL Haus                nanocore
...         ...         ...                     ...
31547   1163859  Threat Fox                     rat
31548   1163860  Threat Fox                     rat
31549   1163860  Threat Fox                nanocore
31550   1163861  Threat Fox               remcosrat
31551   1163861  Threat Fox                     rat

[31552 rows x 3 columns]

### Save dataset into DataWrangling folder

In [6]:
df.to_csv(r'C:\Users\leona\OneDrive\Desktop\Tesi\Pipeline\Datasets\Pipeline\IocSegnalations\IntegratedDataset\PostDataCleaning\Tags.csv')